config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#show'

  root 'welcomes#show'
  resource :session, only: [:new, :create]
  resources :users, only: [:new, :create]

  resource :dashboard, only: :show

  namespace :admin do
    resource :adashboard, only: :show
    resource :user, only: :show
  end

  resource :project, only: :show
end

app/controllers/admin/adashboards_controller.rb
module Admin
	class AdashboardsController < ApplicationController
	  def show
	  end
	end
end

app/controllers/admin/users_controller.rb
module Admin
	class UsersController < ApplicationController
	  def show
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	

  def new
  end

  def create
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/adashboards/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/star.png" type="favicon/ico" />

    <title>Grafika Saran</title>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/owl.theme.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox-theme.css">
    <link rel="stylesheet" href="css/main.css">

  </head> 
	
    <body id="body">
    	


        <header id="navigation" class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<!-- /responsive nav button -->
					
					<!-- logo -->
                    <a class="navbar-brand" href="#body">
						<h1 id="logo">
							Logo
						</h1>
					</a>
					<!-- /logo -->
                </div>

				<!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="Navigation">
                    <ul id="nav" class="nav navbar-nav">
                        <li class="current"><a href="#body">Početna</a></li>
                        <li><a href="#">Uposlenici</a></li>
                        <li><a href="#">Projekti</a></li>
                        <li><a href="#">Poslovanje</a></li>
                        <li><a href="#">Uredi profil</a></li>
                        <li><a href="#">Odjava</a></li>
                    </ul>
                </nav>
				<!-- /main nav -->
				
            </div>
        </header>

<section id="about" class="bg-one brown">
			<div class="container">
				<div class="row">
				
					<!-- section title -->
					<div class="title text-center wow fadeIn" data-wow-duration="1500ms" >
						<h2>Admin <span class="color">panel</span></h2>
						<div class="border"></div>
					</div>
					<!-- /section title -->
					
					<!-- About item -->
					<div class="col-md-4 text-center wow fadeInUp" data-wow-duration="500ms" >
						<div class="wrap-about">							
							<div class="icon-box">
								<i class="fa fa-lightbulb-o fa-4x"></i>
							</div>					
							<!-- Express About Yourself -->
							<div class="about-content text-center">
								<h3 class="ddd">Uposlenici</h3>								
								<p>Pregled, pretraživanje, brisanje, uređivanje svih uposlenika kompanije</p>
							</div>
						</div>
					</div> 
					<!-- End About item -->
					
					<!-- About item -->
					<div class="col-md-4 text-center wow fadeInUp" data-wow-duration="500ms" data-wow-delay="250ms">
						<div class="wrap-about">
							<div class="icon-box">
								<i class="fa fa-users fa-4x"></i>
							</div>
							<!-- Express About Yourself -->
							<div class="about-content text-center">
								<h3>Projekti</h3>
								<p>Unos novih, pregled i uređivanje postojećih projekata unutar kompanije</p>
							</div>
						</div>
					</div> 
					<!-- End About item -->
					
					<!-- About item -->					
					<div class="col-md-4 text-center wow fadeInUp" data-wow-duration="500ms" data-wow-delay="500ms">
						<div class="wrap-about kill-margin-bottom">
							<div class="icon-box">
								<i class="fa fa-users fa-4x"></i>
							</div>
							<!-- Express About Yourself -->
							<div class="about-content text-center">
								<h3>Poslovanje</h3>
								<p>Pregled grafika kako bi omogućili uvid u poslovanje kompanije</p>
							</div>
						</div>
					</div> 
					<!-- End About item -->
					
				</div> 		<!-- End row -->
			</div>   	<!-- End container -->
		</section>   <!-- End section -->

		</body>
		</html>

app/views/admin/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/star.png" type="favicon/ico" />

    <title>Grafika Saran</title>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/owl.theme.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox-theme.css">
    <link rel="stylesheet" href="css/main.css">

  </head> 
    
    <body id="body">

<header id="navigation" class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <a class="navbar-brand" href="#body">
                        <h1 id="logo">
                            Logo
                        </h1>
                    </a>
                    <!-- /logo -->
                    </div>
                    <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="Navigation">
                    <ul id="nav" class="nav navbar-nav">
                        <li><a href="#body">Početna</a></li>
                        <li class="current"><a href="#">Uposlenici</a></li>
                        <li><a href="#">Projekti</a></li>
                        <li><a href="#">Poslovanje</a></li>
                        <li><a href="#">Uredi profil</a></li>
                        <li><a href="#">Odjava</a></li>
                    </ul>
                </nav>
                <!-- /main nav -->
                
                
            </div>
        </header>

<section id="showcase">
            <div class="container">
                <div class="row wow fadeInDown" data-wow-duration="500ms">
                    <div class="col-lg-12">
                    
                        <!-- section title -->
                        <div class="title text-center">
                            <h2>Uposlenici <span class="color">grafike</span></h2>
                            <div class="border"></div>
                        </div>
                        <!-- /section title -->
                        
                    </div> <!-- /end col-lg-12 -->
                </div> <!-- end row -->
            </div>  <!-- end container -->
    
            <div class="col-md-3 col-sm-6 wow fadeInDown" data-wow-duration="500ms">
                       <article class="team-mate">
                            <div class="member-photo">
                                <!-- member photo -->
                                <img class="img-responsive" src="http://navigator-upload-prod.s3.amazonaws.com/attachments/files/000/002/666/medium/grafikasaran.jpg" alt="Projekat">
                                <!-- /member photo -->
                                
                                <!-- member social profile -->
                                <div class="mask">
                                    <ul class="clearfix">
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                    </ul>
                                </div>
                                <!-- /member social profile -->
                            </div>
                            
                            <!-- member name & designation -->
                            <div class="member-title">
                                <h3>Projekat 1</h3>
                                <span>P1</span>
                            </div>
                            <!-- /member name & designation -->
                            
                            <!-- about member -->
                           <div class="member-info">
                               <p>Kratki opis prvog projekta</p>
                           </div>
                           <!-- /about member -->
                           
                       </article>
                    </div>
                    <!-- end team member -->
                    
                    <!-- team member -->
                    <div class="col-md-3 col-sm-6 wow fadeInDown" data-wow-duration="500ms" data-wow-delay="200ms">
                       <article class="team-mate">
                            <div class="member-photo">
                                <!-- member photo -->
                                <img class="img-responsive" src="http://navigator-upload-prod.s3.amazonaws.com/attachments/files/000/002/666/medium/grafikasaran.jpg" alt="Projekat">
                                <!-- /member photo -->
                                
                                <!-- member social profile -->
                                <div class="mask">
                                    <ul class="clearfix">
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                    </ul>
                                </div>
                                <!-- /member social profile -->
                            </div>
                            
                            <!-- member name & designation -->
                            <div class="member-title">
                                <h3>Projekat 2</h3>
                                <span>P2</span>
                            </div>
                            <!-- /member name & designation -->
                            
                            <!-- about member -->
                           <div class="member-info">
                               <p>Kratki opis drugog projekta</p>
                           </div>
                           <!-- /about member -->
                        </article>
                    </div>
                    <!-- end team member -->
                    
                    <!-- team member -->
                    <div class="col-md-3 col-sm-6 wow fadeInDown" data-wow-duration="500ms" data-wow-delay="400ms">
                       <article class="team-mate">
                            <div class="member-photo">
                                <!-- member photo -->
                                <img class="img-responsive" src="http://navigator-upload-prod.s3.amazonaws.com/attachments/files/000/002/666/medium/grafikasaran.jpg" alt="Projekat">
                                <!-- /member photo -->
                                
                                <!-- member social profile -->
                                <div class="mask">
                                    <ul class="clearfix">
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                    </ul>
                                </div>
                                <!-- /member social profile -->
                            </div>
                            
                            <!-- member name & designation -->
                            <div class="member-title">
                                <h3>Projekat 3</h3>
                                <span>P3</span>
                            </div>
                            <!-- /member name & designation -->
                            
                            <!-- about member -->
                           <div class="member-info">
                               <p>Kratki opis trećeg projekta</p>
                           </div>
                           <!-- /about member -->
                       </article>
                    </div>
                    <!-- end team member -->
                    
                    <!-- team member -->
                    <div class="col-md-3 col-sm-6 wow fadeInDown" data-wow-duration="500ms" data-wow-delay="600ms">
                       <article class="team-mate kill-margin-bottom">
                            <div class="member-photo">
                                <!-- member photo -->
                                <img class="img-responsive" src="http://navigator-upload-prod.s3.amazonaws.com/attachments/files/000/002/666/medium/grafikasaran.jpg" alt="Meghna">
                                <!-- /member photo -->
                                
                                <!-- member social profile -->
                                <div class="mask">
                                    <ul class="clearfix">
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                    </ul>
                                </div>
                                <!-- /member social profile -->
                            </div>
                            
                            <!-- member name & designation -->
                            <div class="member-title">
                                <h3>Projekat 4</h3>
                                <span>P4</span>
                            </div>
                            <!-- /member name & designation -->
                            
                            <!-- about member -->
                           <div class="member-info">
                               <p>Kratki opis četvrtog projekta</p>
                           </div>
                           <!-- /about member -->
                       </article>
                    </div>
                    <!-- end team member -->
            
        </section>   <!-- End section -->
        </body>
        </html>

app/views/dashboards/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/star.png" type="favicon/ico" />

    <title>Grafika Saran</title>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/owl.theme.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox-theme.css">
    <link rel="stylesheet" href="css/main.css">

  </head> 
	
    <body id="body">

<header id="navigation" class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<!-- /responsive nav button -->
					
					<!-- logo -->
                    <a class="navbar-brand" href="#body">
						<h1 id="logo">
							Logo
						</h1>
					</a>
					<!-- /logo -->
					</div>
					<!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="Navigation">
                    <ul id="nav" class="nav navbar-nav">
                        <li><a href="#">Uredi profil</a></li>
                        <li><a href="#">Odjava</a></li>
                    </ul>
                </nav>
                <!-- /main nav -->
                
				
            </div>
        </header>

<section id="showcase">
			<div class="container">
				<div class="row wow fadeInDown" data-wow-duration="500ms">
					<div class="col-lg-12">
					
						<!-- section title -->
						<div class="title text-center">
							<h2>Moji <span class="color">projekti</span></h2>
							<div class="border"></div>
						</div>
						<!-- /section title -->
					
						<!-- portfolio item filtering -->
						<div class="portfolio-filter clearfix">
							<ul class="text-center">
							    <li><a href="javascript:void(0)" class="filter" data-filter="all">Kategorija 1</a></li>
								<li><a href="javascript:void(0)" class="filter" data-filter=".app">Kategorija 2</a></li>
								<li><a href="javascript:void(0)" class="filter" data-filter=".web">Kateorija 3</a></li>
								<li><a href="javascript:void(0)" class="filter" data-filter=".photoshop">Kateorija 4</a></li>
								<li><a href="javascript:void(0)" class="filter" data-filter=".illustrator">Ostalo</a></li>
							</ul>
						</div>
						<!-- /portfolio item filtering -->
						
					</div> <!-- /end col-lg-12 -->
				</div> <!-- end row -->
			</div>	<!-- end container -->
	
			

<div class="container">            
  <table class="table">
    <thead>
      <tr>
        <th>Ime</th>
        <th>Prezime</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Neko</td>
        <td>Nekić</td>
        <td>neko@gmail.com</td>
      </tr>
      <tr>
        <td>Kanita</td>
        <td>Imamović</td>
        <td>kanitaimamovic@gmail.com</td>
      </tr>
      <tr>
        <td>Nermin</td>
        <td>Ćatić</td>
        <td>nermincatic@gmail.com</td>
      </tr>
    </tbody>
  </table>
</div>

</body>
</html>

			
		</section>   <!-- End section -->
		</body>
		</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StamparijaApp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600', media: 'all'%>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Hind:400,500,600,700,300&subset=latin,latin-ext', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>stamparijaApp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600', media: 'all'%>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Hind:400,500,600,700,300&subset=latin,latin-ext', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/star.png" type="favicon/ico" />

    <title>Grafika Saran</title>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/owl.theme.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox-theme.css">
    <link rel="stylesheet" href="css/main.css">

  </head> 
	
    <body id="body">

<header id="navigation" class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<!-- /responsive nav button -->
					
					<!-- logo -->
                    <a class="navbar-brand" href="#body">
						<h1 id="logo">
							Logo
						</h1>
					</a>
					<!-- /logo -->
                    </div>
                    <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="Navigation">
                    <ul id="nav" class="nav navbar-nav">
                        <li><a href="#">Uredi profil</a></li>
                        <li><a href="#">Odjava</a></li>
                    </ul>
                </nav>
                <!-- /main nav -->

                
				
            </div>
        </header>

        <section id="pricing" class="bg-one">
            <div class="container">
                <div class="row">
                    
                    <!-- section title -->
                    <div class="title text-center wow fadeInDown" data-wow-duration="500ms">
                        <h2>Naziv<span class="color"> projekta</span></h2>
                        <div class="border"></div>
                    </div>
                    <!-- /section title -->
                    
                    <!-- single pricing table -->
                    <article class="col-md-4 col-sm-4 col-xs-6 text-center wow fadeInUp" data-wow-duration="200ms">
                        <div class="pricing">
                            
                            <!-- plan name & value -->
                            <div class="price-title">
                                <h3>Zadaci</h3>
                                
                            </div>
                            <!-- /plan name & value -->
                            
                            <!-- plan description -->
                            <ul>
                                <li>Zadatak 1</li>
                                <li>Zadatak 3</li>
                                <li>Zadatak 5</li>
                                <li>Zadatak 9</li>
                            </ul>
                            <!-- /plan description -->
                            </br></br>                           
                        </div>
                    </article>
                    <!-- end single pricing table -->
                    
                    <!-- single pricing table -->
                    <article class="col-md-4 col-sm-4 col-xs-6 text-center wow fadeInUp" data-wow-duration="500ms" data-wow-delay="400ms">
                        <div class="pricing">
                        
                            <!-- plan name & value -->
                            <div class="price-title">
                                <h3>U toku</h3>
                            </div>
                            <!-- /plan name & value -->
                            
                            <!-- plan description -->
                            <ul>
                                <li>Zadatak 2</li>
                                <li>Zadatak 4</li>
                                <li>Zadatak 6</li>
                                <li>Zadatak 7</li>
                                <li>Zadatak 8</li>
                                <li>Zadatak 10</li>
                            </ul>
                            <!-- /plan description -->
                            </br></br>                            
                        </div>
                    </article>
                    <!-- end single pricing table -->
                    
                    <!-- single pricing table -->
                    <article class="col-md-4 col-sm-4 col-xs-6 text-center wow fadeInUp" data-wow-duration="500ms" data-wow-delay="600ms">
                        <div class="pricing">
                            
                            <!-- plan name & value -->
                            <div class="price-title">
                                <h3>Urađeno</h3>
                            </div>
                            <!-- /plan name & value -->
                            
                            <!-- plan description -->
                            <ul>
                                <li>Zadatak 11</li>
                                <li>Zadatak 12</li>
                                <li>Zadatak 13</li>
                                <li>Zadatak 14</li>
                                <li>Zadatak 15</li>
                            </ul>
                            <!-- /plan description --> 
                            </br></br>                           
                        </div>
                    </article>
                    <!-- end single pricing table -->
                    
                    
                </div>       <!-- End row -->
            </div>      <!-- End container -->
        </section>   <!-- End section -->

        </body>
        </html>

app/views/welcomes/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/star.png" type="favicon/ico" />

    <title>Grafika Saran</title>

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/owl.carousel.css">
    <link rel="stylesheet" href="css/owl.theme.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox.css">
    <link rel="stylesheet" href="nivo-lightbox/nivo-lightbox-theme.css">
    <link rel="stylesheet" href="css/main.css">

  </head> 
  <body>

    <!--== 4. Header ==-->

        <section class="header" id="header">
            <div class="navigationbar  navbar-fixed-top">
                <div class="container">
                    <a href="#" class="logo">
                       logo 
                    </a>
                </div> <!-- /.container -->
            </div> <!-- /.navigation-bar -->
            <div class="header-description text-center">
                <div class="header-content wow bounce animated">
                    <h1 class="heading">grafika šaran</h1>
                    <p class="heading-subtitle">
                        pojednostavite svoj posao
                    </p> 
                    <hr>
                    <%= link_to 'Prijava', new_session_path, class: "btn btn-primary btn-xl" %>
                    &nbsp; 
                    <%= link_to 'Registracija', new_user_path, class: "btn btn-primary btn-xl" %>
		        	

                </div> <!-- /.header-content -->   
            </div> <!-- /.header-description -->
        </section> <!-- /#header -->

  </body>
</html>